name : Premier workflow
on: 
  - workflow_dispatch
  - push
jobs:
  premier-jobs:
    name: premier job
    runs-on: ubuntu-latest
    steps:
      - name: Dit bonjour
        run: echo 'Hello World !'
      - name: Dit au revoir
        run: echo 'Bye World !'
  second-jobs:
    name: second job
    runs-on: ubuntu-latest
    steps:
      - name: etape 2
        run: echo 'second job'

