name : Premier workflow
on: 
  - workflow_dispatch
  - push
jobs:
  first-jobs:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: welcome
        run: echo 'Bienvenue dans la CI/CD pour l'API de satisfaction !'
      - name: print date
        run: date

